[package]
name = "chalk"
version = "0.1.0"
description = "Model of the Rust trait system"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang-nursery/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]

[dependencies]
diff = "0.1.11"
docopt = "0.8.1"
ena = "0.4"
error-chain = "0.11.0"
itertools = "0.6.0"
lalrpop-intern = "0.14"
petgraph = "0.4.5"
rustyline = "1.0"
serde = "1.0"
serde_derive = "1.0"
stacker = "0.1.2"

[dependencies.chalk-parse]
version = "0.1.0"
path = "chalk-parse"

[dependencies.chalk-macros]
version = "0.1.0"
path = "chalk-macros"

[dependencies.chalk-engine]
version = "0.5.0"
path = "chalk-engine"

[workspace]
