[package]
name = "chalk"
version = "0.1.0"
description = "Model of the Rust trait system"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]
edition = "2018"

[features]
bench = []

[dependencies]
diff = "0.1.11"
docopt = "1.0.0"
itertools = "0.8.0"
rustyline = "1.0"
salsa = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
stacker = "0.1.5"
string_cache = "0.8.0"

[dependencies.chalk-parse]
version = "0.1.0"
path = "chalk-parse"

[dependencies.chalk-ir]
version = "0.1.0"
path = "chalk-ir"

[dependencies.chalk-solve]
version = "0.1.0"
path = "chalk-solve"

[dependencies.chalk-macros]
version = "0.1.0"
path = "chalk-macros"

[dependencies.chalk-engine]
version = "0.9.0"
path = "chalk-engine"

[dependencies.chalk-rust-ir]
version = "0.1.0"
path = "chalk-rust-ir"

[dependencies.chalk-derive]
version = "0.1.0"
path = "chalk-derive"

[dependencies.chalk-integration]
version = "0.1.0"
path = "chalk-integration"

[workspace]
